### ISSUE TITLE
Open on right

### ISSUE THREAD

**Issue by wolfadex** [gauravchl/react-simple-sidenav#2]
I love how simple this component is. The only feature I would like is to have the menu optionally open from the right.

**Comment by gauravchl** [comment]
@wolfadex Great idea! Just released new version with this feature. Now you can use 'openFromRight' props to do that.
check it out: https://gauravchl.github.io/react-simple-sidenav/demo/
<img width="521" alt="screen shot 2017-01-29 at 12 04 54 pm" src="https://cloud.githubusercontent.com/assets/3471415/22402403/cc131f12-e61b-11e6-88de-901ce1a77cc5.png">

cheers!
