### ISSUE TITLE
Mobile View Not Responsive

### ISSUE THREAD

**Issue by cpurtlebaugh** [gauravchl/react-simple-sidenav#4]
Hi Gaurav, I really like this component and am getting it to work nicely with react-headroom. In your demo versions when using the dev tools to checkout mobile view everything looks fine. That said, when I check the mobile view in my app (starting from scratch) it is not translating and the sidenav is out of view. I'm not able to pinpoint the difference in the elements currently, nor am I seeing any media queries...if you have any input or if this is a bug please let me know. Thanks in advance for your help!

Casper

**Comment by gauravchl** [comment]
Hi Casper,
Thanks! I'm glad you like it.

About the responsive issue, it might be possible that some media quires based css or any css reset rules on your app is overriding sidenav's css. Can you share the code if possible. 
Also make sure there is no css overrides for nav element(`<nav>`), if this is the case you can use prop `navStyle` to set default css with `!important` rule to make it work.

<img width="1525" alt="screen shot 2017-03-15 at 10 15 54 am" src="https://cloud.githubusercontent.com/assets/3471415/23934083/c4a6c060-0968-11e7-8361-ae3895e97122.png">


- Gaurav
